### ISSUE TITLE
(Test) Just for test. And I made 'test' label.

### ISSUE THREAD

**Issue by taelee42** [4Eat42/yebalja.com#4]
__Test__
- I'm just testing Issues and Pull requests features in github.
- Since there was no label name 'test', I've made 'test' label.
<br>

---
<br>

__테스트__
- 이슈와 풀 리퀘스트 기능을 테스트 해보고 있습니다.
- 테스트를 하려다가 맞는 라벨이 없어서 테스트 라벨을 한번 만들어봤습니다.
<br>

**Comment by kirrikirri42** [comment]
This is a comment

**Comment by kirrikirri42** [comment]
This is the last comment because I will close
